=== CERTCC/cvd/schema/report_methods.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://democert.org/cvd/report_methods.schema.json",
    "title": "Results or response to a vendor search by a security researcher",
    "description": "Results presented to a Vulnerability reporting discovery search for a vendor and product and version following CERT Coordinated Vulnerability Disclosure (CVD) guide 2021.08.1101",
    "type": "object",
    "properties": {
	"document_type": {
	    "type": "string",
	    "description": "A string representing the type of document that is being considered. Default report gives CERT's contact when no vendor-product matches in CERT's directory",
	    "enum": ["report_methods","default_report"]
	},
	"version": {
	    "type": "string",
	    "description": "Version of the vendor search protocol submitted",
	    "example": "1.0.0"
	},
	"title": {
	    "type": "string",
	    "description": "Optional title given to your search performed",
	    "example": "Search to report buffer overflow in Apache/httpd/2.0.1"
	},
	"stakeholders": {
	    "type": "array",
	    "description": "An array of search criterea presented by the security researcher for finding vendor contacts",
	    "minItems": 1,
	    "items": {
		"type": "object",
		"description": "Information about the stakeholder able to accept report from the security researcher",
		"properties": {
		    "type" : {
			"type": "string",
			"description": "Type of contact/stakeholder who is able to accept vulnerability report from the researcher",
			"enum": ["vendor","vendor_psirt","vendor_bugbounty","bugbounty_third_party","CERT","CSIRT"]
		    },
		    "name": {
			"type": "string",
			"description": "Official or Friendly name of the stakeholder able to accept the report",
			"examples": ["Microsoft","Apache","John Wayne"]
		    },
		    "method": {
			"type": "string",
			"description": "Methods in which the Stakeholder can be reached. Either email or web forms ",
			"enum": ["email","web","api","pgp_email","smime_email"]
		    },
		    "contact_url": {
			"type": "string",
			"format": "uri",
			"description": "URL of the stakeholder's contact method",
			"examples": ["https://google.com/security","mailto:security@intel.com"]
		    },
		    "access": {
			"type": "string",
			"description": "Access, if any, required to reach the stakeholder",
			"enum": ["public","registered_user","approval_required"]
		    },
		    "access_tokens": {
			"type": "array",
			"description": "Type of access verificaction(s) required for becoming a trusted user or reporter",
			"items": {
			    "type": "string",
			    "examples": ["password","2fa","oauth"]
			}
		    },
		    "access_security": {
			"type": "array",
			"description": "Type of secure communications methods supported by the stakeholder",
			"items" : {
			    "type": "string",
			    "enum": ["pgp","dane","smime","https"]
			}
		    },
		    "disclosure_rewards": {
			"type": "array",
			"description": "Type of rewards (financial and other) provided by the stakeholder for coordinated disclosure of vulnerabilities",
			"items": {
			    "type": "string",
			    "enum": ["bounty","swag","hall_of_fame"]
			}
		    },
		    "disclosure_timelines": {
			"type": "object",
			"type": "string",
			"format": "duration",
			"description": "ISO 8601 ABNF denotion of duration",
			"examples": ["30D"]
		    },
		    "fees": {
			"type": "string",
			"description": "Optional information on any type of fees to be paid to be in the Bug Bounty or security reporting program",
			"examples": ["USD100 one time","EUR20 yearly"]
		    },
		    "policy_url": {
			"type": "string",
			"description": "An URI where the policy with details of terms and conditions for reporting vulnerabilities is provided",
			"format": "uri"
		    },
		    "last_verified": {
			"type": "integer",
			"description": "Timestamp in UNIX epoch seconds on when the information was last verified to be active"
		    }
		    
		}
	    },
	    "required": ["type","name","method","url","access","access_tokens","policy_url","contact_url","last_verified"]
	},
	"inputs": {
	    "type": "array",
	    "minItems": 1,
	    "items": {
		"type": "object",
		"properties": {
		    "vendor_search_string": {
			"type": "string",
			"description": "Vendor value provided by the search"
		    },
		    "product_search_string": {
			"type": "string",
			"description": "Product value provided by the search"
		    },
		    "version_search_string": {
			"type": "string",
			"description": "Version value provided by the search"
		    }
		}
	    },
	    "required": ["vendor_search_string","product_search_string"]
	},
	"input_schema": {
	    "type": "string",
	    "format": "uri",
	    "description": "Full URI of the schema used for search submission"
	},
	"timestamp": {
	    "type": "integer",
	    "description": "Time in unix epoch of when the search was performed"
	}
    },
    "required": [ "document_type","version","stakeholders","inputs",
		  "input_schema", "timestamp"]
}

=== CERTCC/cvd/data/report_methods.json
{
    "document_type" : "report_methods",
    "version": "1.0.0",
    "title": "Results for Vulnerability reporting discovery search results for Microsoft/Windows printserver vulnerability that can result in RCE using CERT API",
    "stakeholders": [
	{
	    "type": "vendor_psirt",
	    "name": "Microsoft",
	    "contact_methods":[{
		"method": "email",
		"contact_url": "mailto:security@microsoft.com",
		"contact_id": "security@microsoft.com",
		"access": "public",
		"last_verified": 1629309447
		
	    }],
	    "policy_url": "https://microsoft.com/psirt/terms"
	},
	{
	    "type": "vendor_bugbounty",
	    "name": "Microsoft",
	    "contact_methods": [
		{	    
		    "method": "web",
		    "contact_url": "https://microsoft.com/bugbounty",
		    "contact_id": "Contact-1",
		    "access": "registered_user",
		    "fees": "unknown",
		    "access_tokens": [ "password", "oauth"],
		    "last_verified": 1629309047
		    
		}
	    ],
	    "policy_url": "https://microsoft.com/bugbounty/terms"
	},	
	{
	    "type": "bugbounty_third_party",
	    "name": "Hacker One",
	    "contact_methods": [ {
		"method": "web",
		"contact_url": "https://hackerone.com/sign_up",
		"contact_id": "Contact-2",
		"access": "registered_user",
		"access_tokens": ["password", "2fa"],	    
		"fees": "none",
		"last_verified": 1629309447
		
	    }],
	    "policy_url": "https://www.hackerone.com/terms/finder",
	    "last_verified": 1629309447
	},
	{
	    "type": "CERT",
	    "name": "CERT",
	    "contact_methods": [ {
		"method": "web",
		"contact_url": "https://kb.cert.org/vince",
		"access": "registered_user",
		"access_tokens": [ "api_key", "2fa"],
		"contact_id": "CERT/CC",
		"fees": "none",
		"schema": "https://vuls.cert.org/schemas/vul_report.schema.json",
		"submission": "HTTP_POST",
		"last_verified": 1629309447
		
	    }],
	    "policy_url": "https://vuls.cert.org/confluence/display/Wiki/Vulnerability+Disclosure+Policy"
	}
    ],
    "inputs": [
	{
	    "vendor" : "Microsoft",
	    "product" : "Windows"
	}
    ], 
    "input_schema": "https://democert.org/cvd/vendor_search.schema.json",
    "timestamp": 1629309447
}
